name: Generate & Release
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Generate the script
        uses: ./.github/actions/bashly-generate
      - name: Test the script
        run: ./dist/spark --help
      - name: Cache workspace
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.run_id }}-${{ github.run_attempt }}
  release:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Restore workspace
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: workspace-${{ github.run_id }}-
      # TODO: https://github.com/softprops/action-gh-release
